Repository ShubhangiRoy12/MooVit, pull requests merged in 2025-09, with the labels that each got.

#31 UI-of-Chatbot
  Chatbot/style.css
Labels: gssoc25

#52 Updated Login/Signup method
  index.html
Labels: gssoc25, level2, Frontend, Backend

#48 Added The template for pull request
  .github/pull_request_request.md
Labels: gssoc25, level1

#53 Add MIT License to the project
  LICENSE
Labels: gssoc25

#69 Fix #67: Redesigned Routes page and added time calculation tools
  Routes/route.css
  Routes/route.html
  Routes/route.js
  Vehicles/vechicle.css
  Vehicles/vechicle.html
  Vehicles/vechicle.js
Labels: gssoc25, level3
